### llama modules ###
from shadow import user, srv

### server list and configuration
# notes
# - 'port' needs to be an integar, not a string

servers = {

### Syslog Collectors ###
    '54.41.8.36':{
        'group': 'syslog',
        'host': 'lue1vp10204',
        'jump': False,
        'user': srv['u'],
        'pass': srv['p'],
        'port': 2022,
        },

    '54.56.168.82':{
        'group': 'syslog',
        'host': 'lctcvp6227',
        'jump': False,
        'user': user['u'],
        'pass': user['p'],
        'port': 2022,
        },
# Belgium Servers
    '54.101.204.6':{
        'region': 'Belgium',
        'group': 'syslog',
        'host': 'lamevp1000',
        'jump': True,
        'jump_user': user['u'],
        'jump_pass': user['p'],
        'jump_server': 'ctcjump.merck.com',
        'user': srv['u'],
        'pass': srv['p'],
        'port': 2022,
        },

    '54.101.204.7':{
        'region': 'Belgium',
        'group': 'syslog',
        'host': 'lamevp1001',
        'jump': True,
        'jump_user': user['u'],
        'jump_pass': user['p'],
        'jump_server': 'ctcjump.merck.com',
        'user': srv['u'],
        'pass': srv['p'],
        'port': 2022,
        },

    '54.101.204.8':{
        'region': 'Belgium',
        'group': 'syslog',
        'host': 'lamevp1002',
        'jump': True,
        'jump_user': user['u'],
        'jump_pass': user['p'],
        'jump_server': 'ctcjump.merck.com',
        'user': srv['u'],
        'pass': srv['p'],
        'port': 2022,
        },
# US Servers
    '54.58.40.236':{
        'region': 'US',
        'group': 'syslog',
        'host': 'lctcvp7820',
        'jump': True,
        'jump_user': user['u'],
        'jump_pass': user['p'],
        'jump_server': 'ctcjump.merck.com',
        'user': srv['u'],
        'pass': srv['p'],
        'port': 2022,
        },

    '54.58.41.68':{
        'region': 'US',
        'group': 'syslog',
        'host': 'lctcvp7821',
        'jump': True,
        'jump_user': user['u'],
        'jump_pass': user['p'],
        'jump_server': 'ctcjump.merck.com',
        'user': srv['u'],
        'pass': srv['p'],
        'port': 2022,
        },

    '54.58.41.26':{
        'region': 'US',
        'group': 'syslog',
        'host': 'lctcvp7822',
        'jump': True,
        'jump_user': user['u'],
        'jump_pass': user['p'],
        'jump_server': 'ctcjump.merck.com',
        'user': srv['u'],
        'pass': srv['p'],
        'port': 2022,
        },

    '54.58.40.14':{
        'region': 'US',
        'group': 'syslog',
        'host': 'lctcvp7823',
        'jump': True,
        'jump_user': user['u'],
        'jump_pass': user['p'],
        'jump_server': 'ctcjump.merck.com',
        'user': srv['u'],
        'pass': srv['p'],
        'port': 2022,
        },

# Singapore Servers
    '54.120.96.134':{
        'region': 'Singapore',
        'group': 'syslog',
        'host': 'lskcvp6642',
        'jump': True,
        'jump_user': user['u'],
        'jump_pass': user['p'],
        'jump_server': 'ctcjump.merck.com',
        'user': srv['u'],
        'pass': srv['p'],
        'port': 2022,
        },

    '54.58.40.14':{
        'region': 'Singapore',
        'group': 'syslog',
        'host': 'lskcvp6643',
        'jump': True,
        'jump_user': user['u'],
        'jump_pass': user['p'],
        'jump_server': 'ctcjump.merck.com',
        'user': srv['u'],
        'pass': srv['p'],
        'port': 2022,
        },

### AWS-Prem Servers ###
    '54.41.27.210':{
        'region': 'na',
        'group': 'aws-prem',
        'host': 'lue1vp1012',
        'jump': True,
        'jump_user': user['u'],
        'jump_pass': user['p'],
        'jump_server': 'ctcjump.merck.com',
        'user': srv['u'],
        'pass': srv['p'],
        'port': 2022,
        },

    '54.41.13.111':{
        'region': 'na',
        'group': 'aws-prem',
        'host': 'lue1vp1024',
        'jump': True,
        'jump_user': user['u'],
        'jump_pass': user['p'],
        'jump_server': 'ctcjump.merck.com',
        'user': srv['u'],
        'pass': srv['p'],
        'port': 2022,
        },

    '54.41.13.61':{
        'region': 'na',
        'group': 'aws-prem',
        'host': 'lue1vp1025',
        'jump': True,
        'jump_user': user['u'],
        'jump_pass': user['p'],
        'jump_server': 'ctcjump.merck.com',
        'user': srv['u'],
        'pass': srv['p'],
        'port': 2022,
        },

    '54.41.1.36':{
        'region': 'na',
        'group': 'aws-prem',
        'host': 'lue1vp1026',
        'jump': True,
        'jump_user': user['u'],
        'jump_pass': user['p'],
        'jump_server': 'ctcjump.merck.com',
        'user': srv['u'],
        'pass': srv['p'],
        'port': 2022,
        },

    '54.41.13.71':{
        'region': 'na',
        'group': 'aws-prem',
        'host': 'lue1vp1027',
        'jump': True,
        'jump_user': user['u'],
        'jump_pass': user['p'],
        'jump_server': 'ctcjump.merck.com',
        'user': srv['u'],
        'pass': srv['p'],
        'port': 2022,
        },

    '54.41.1.79':{
        'region': 'na',
        'group': 'aws-prem',
        'host': 'lue1vp1028',
        'jump': True,
        'jump_user': user['u'],
        'jump_pass': user['p'],
        'jump_server': 'ctcjump.merck.com',
        'user': srv['u'],
        'pass': srv['p'],
        'port': 2022,
        },

    '54.41.10.246':{
        'region': 'na',
        'group': 'aws-prem',
        'host': 'lue1vp1030',
        'jump': True,
        'jump_user': user['u'],
        'jump_pass': user['p'],
        'jump_server': 'ctcjump.merck.com',
        'user': srv['u'],
        'pass': srv['p'],
        'port': 2022,
        },

    '10.62.164.109':{ #
        'region': 'na',
        'group': 'aws-prem',
        'host': 'lue1vp11642',
        'jump': True,
        'jump_user': user['u'],
        'jump_pass': user['p'],
        'jump_server': 'ctcjump.merck.com',
        'user': srv['u'],
        'pass': srv['p'],
        'port': 2022,
        },

    '10.62.166.44':{
        'region': 'na',
        'group': 'aws-prem',
        'host': 'lue1vp11643',
        'jump': True,
        'jump_user': user['u'],
        'jump_pass': user['p'],
        'jump_server': 'ctcjump.merck.com',
        'user': srv['u'],
        'pass': srv['p'],
        'port': 2022,
        },

    '10.62.161.201':{
        'region': 'na',
        'group': 'aws-prem',
        'host': 'lue1vp11644',
        'jump': True,
        'jump_user': user['u'],
        'jump_pass': user['p'],
        'jump_server': 'ctcjump.merck.com',
        'user': srv['u'],
        'pass': srv['p'],
        'port': 2022,
        },

    '10.62.166.129':{
        'region': 'na',
        'group': 'aws-prem',
        'host': 'lue1vp11659',
        'jump': True,
        'jump_user': user['u'],
        'jump_pass': user['p'],
        'jump_server': 'ctcjump.merck.com',
        'user': srv['u'],
        'pass': srv['p'],
        'port': 2022,
        },

    '54.56.139.152':{
        'region': 'na',
        'group': 'aws-prem',
        'host': 'lctcsp1020',
        'jump': True,
        'jump_user': user['u'],
        'jump_pass': user['p'],
        'jump_server': 'ctcjump.merck.com',
        'user': srv['u'],
        'pass': srv['p'],
        'port': 2022,
        },

    '10.62.162.218':{
        'region': 'na',
        'group': 'aws-prem',
        'host': 'lue1vp12213',
        'jump': True,
        'jump_user': user['u'],
        'jump_pass': user['p'],
        'jump_server': 'ctcjump.merck.com',
        'user': srv['u'],
        'pass': srv['p'],
        'port': 2022,
        },

    '155.91.32.206':{
        'region': 'na',
        'group': 'aws-prem',
        'host': 'lctcvp1186',
        'jump': True,
        'jump_user': user['u'],
        'jump_pass': user['p'],
        'jump_server': 'ctcjump.merck.com',
        'user': srv['u'],
        'pass': srv['p'],
        'port': 2022,
        },

    '155.91.32.8':{
        'region': 'na',
        'group': 'aws-prem',
        'host': 'lctcvp1220',
        'jump': True,
        'jump_user': user['u'],
        'jump_pass': user['p'],
        'jump_server': 'ctcjump.merck.com',
        'user': srv['u'],
        'pass': srv['p'],
        'port': 2022,
        },

    '54.58.5.237':{
        'region': 'na',
        'group': 'aws-prem',
        'host': 'lctcvp7021',
        'jump': True,
        'jump_user': user['u'],
        'jump_pass': user['p'],
        'jump_server': 'ctcjump.merck.com',
        'user': srv['u'],
        'pass': srv['p'],
        'port': 2022,
        },
### Phnatom Servers ###
    '54.41.8.114':{ #
        'region': 'na',
        'group': 'phantom',
        'host': 'lue1vd7375',
        'jump': False,
        'user': user['u'],
        'pass': user['p'],
        'port': 2022,
        },

    '54.41.4.222':{
        'region': 'na',
        'group': 'phantom',
        'host': 'lue1vd7377',
        'jump': False,
        'user': user['u'],
        'pass': user['p'],
        'port': 2022,
        },

    '54.41.4.25':{
        'region': 'na',
        'group': 'phantom',
        'host': 'lue1vp1037',
        'jump': False,
        'user': user['u'],
        'pass': user['p'],
        'port': 2022,
        },

    '54.41.12.101':{
        'region': 'na',
        'group': 'phantom',
        'host': 'lue1vp1038',
        'jump': False,
        'user': user['u'],
        'pass': user['p'],
        'port': 2022,
        },

    '54.41.14.9':{
        'region': 'na',
        'group': 'phantom',
        'host': 'lue1vt1028',
        'jump': False,
        'user': user['u'],
        'pass': user['p'],
        'port': 2022,
        },

    '54.41.4.180':{
        'region': 'na',
        'group': 'phantom',
        'host': 'lue1vt10210 ',
        'jump': False,
        'user': user['u'],
        'pass': user['p'],
        'port': 2022,
        },
        
}